In [12]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.linalg import eigh


In [13]:
eps0 = 0
t    = -1
s    = 0

In [3]:
#eigen value Li_3 linear

H = np.array([[eps0 , t     , 0   ],
              [t    , eps0  , t   ],
              [0    , t     , eps0]])

S = np.array([[1    , s     , 0],
              [s    , 1     , s],
              [0    , s     , 1]])

E, C = eigh(H, S)
E/= np.sqrt(2)
print('E-value:', E)
print('E-vector', C)

E-value: [-1.00000000e+00 -4.29322157e-18  1.00000000e+00]
E-vector [[-5.00000000e-01 -7.07106781e-01  5.00000000e-01]
 [-7.07106781e-01 -4.85722573e-17 -7.07106781e-01]
 [-5.00000000e-01  7.07106781e-01  5.00000000e-01]]


In [4]:
#eigen value Li_3 Segitiga

H = np.array([[eps0 , t     , t   ],
              [t    , eps0  , t   ],
              [t    , t     , eps0]])

S = np.array([[1    , s     , s],
              [s    , 1     , s],
              [s    , s     , 1]])

E, C = eigh(H, S)
print('E-value:', E)
print('E-vector', C)

E-value: [-2.  1.  1.]
E-vector [[ 0.57735027 -0.42250331  0.69868277]
 [ 0.57735027  0.81632869  0.01655721]
 [ 0.57735027 -0.39382538 -0.71523999]]


In [8]:
#eigen value benzene

H = np.array([[eps0 , t     , 0   , 0    , 0     , t   ],
              [t    , eps0  , t   , 0    , 0     , 0   ],
              [0    , t     , eps0, t    , 0     , 0   ],
              [0    , 0     , t   , eps0 , t     , 0   ],
              [0    , 0     , 0   , t    , eps0  , t   ],
              [t    , 0     , 0   , 0    , t     , eps0]])

S = np.array([[1    , s     , 0   , 0    , 0     , s],
              [s    , 1     , s   , 0    , 0     , 0],
              [0    , s     , 1   , s    , 0     , 0],
              [0    , 0     , s   , 1    , s     , 0],
              [0    , 0     , 0   , s    , 1     , s],
              [s    , 0     , 0   , 0    , s     , 1]])

E, C = eigh(H, S)
print('E-value:', E)
print('E-vector', C)

E-value: [-2. -1. -1.  1.  1.  2.]
E-vector [[ 4.08248290e-01 -2.25629369e-02  5.76909219e-01 -4.81576194e-18
   5.77350269e-01 -4.08248290e-01]
 [ 4.08248290e-01 -5.10899508e-01  2.68914533e-01 -5.00000000e-01
  -2.88675135e-01  4.08248290e-01]
 [ 4.08248290e-01 -4.88336571e-01 -3.07994686e-01  5.00000000e-01
  -2.88675135e-01 -4.08248290e-01]
 [ 4.08248290e-01  2.25629369e-02 -5.76909219e-01  2.32525553e-17
   5.77350269e-01  4.08248290e-01]
 [ 4.08248290e-01  5.10899508e-01 -2.68914533e-01 -5.00000000e-01
  -2.88675135e-01 -4.08248290e-01]
 [ 4.08248290e-01  4.88336571e-01  3.07994686e-01  5.00000000e-01
  -2.88675135e-01  4.08248290e-01]]


C60 = fullerene

In [39]:
file = open('C6.xyz')
data = file.readlines()

n = int(data[0])
species = data[1]
atomlist = []
coordlist = []

if n != (len(data)-2):
    raise ValueError('n and number of atoms input mismatch')
    
for i in range(n):
    # try:
    #     row = data[i+2].split()
    # except:
    #     print('error')
    #     break
    row = data[i+2].split()
    atomlist.append([row[0], i+1])
    coordrow = list(map(float, row[1:4]))
    coordlist.append(np.array(coordrow))

coordlist = np.array(coordlist)

print(coordlist)

[[ 1.3899 -0.0572  0.0114]
 [ 0.6825 -0.0924  1.2087]
 [-0.7075 -0.0352  1.1973]
 [-1.3898  0.0572 -0.0114]
 [-0.6824  0.0925 -1.2088]
 [ 0.7075  0.0352 -1.1973]
 [-1.389   0.057  -0.011 ]
 [-1.3891  0.0571 -0.0111]]


In [40]:
def interatomic_distance(atom1coord, atom2coord):
    #atomcoord = array berisi xyz
    deltax = atom1coord[0] - atom2coord[0]
    deltay = atom1coord[1] - atom2coord[1]
    deltaz = atom1coord[2] - atom2coord[2]

    r = np.sqrt(deltax ** 2 + deltay ** 2 + deltaz ** 2)
    return r

def rel_err(a, b):
    return abs(a - b) / b

min_distance_tol = 0.01
min_distance_list = []

for i in range(n):
    atomcoord_i = coordlist[i]
    id_i = atomlist[i]
    min_distance = 0

    for j in range(n):
        if i == j :
            continue
        atomcoord_j = coordlist[j]
        distance_ij = interatomic_distance(atomcoord_i, atomcoord_j)
        if min_distance == 0:
            min_distance = distance_ij
            nearest_neighbor = [j+1]
        else:
            if rel_err(distance_ij, min_distance) < min_distance_tol:
                nearest_neighbor.append(j+1)
            else:
                if distance_ij < min_distance:
                    min_distance = distance_ij
                    nearest_neighbor = [j+1]

    min_distance_list.append([id_i, nearest_neighbor])
                
print(min_distance_list)

[[['C', 1], [2, 6]], [['C', 2], [1, 3]], [['C', 3], [2, 4, 7, 8]], [['C', 4], [8]], [['C', 5], [4, 6, 7, 8]], [['C', 6], [1, 5]], [['X', 7], [8]], [['Y', 8], [7]]]


In [17]:
x, y, z = np.loadtxt('C60-Ih.xyz', unpack = True)

print(z)

[ 2.5874  1.5918  3.1679  1.1654 -0.193   0.6682 -0.6859 -1.1207  3.1271
  2.5542  3.4379  2.283   1.099   1.6326  0.4373  0.1707  2.5955  2.2854
  3.1738  2.5512  1.6319  1.1007  0.1746  0.4399  1.7365  1.1637  2.7453
  1.5942  0.6701 -0.1897 -1.117  -0.6878  1.7358  0.7293  2.7435  0.7302
 -0.4594 -0.464  -1.658  -1.6531 -2.5979 -2.3083 -2.5845 -3.1671 -1.7378
 -1.1811 -1.6107 -2.7271 -1.7418 -0.7513 -0.7491 -2.7355 -2.6051 -1.6107
 -1.1824 -3.1786 -3.1661 -2.5908 -2.3171 -3.4585]


In [ ]:
def structure(n, acc):

In [ ]:
def hamiltonian(n, acc, t):
    struc = structure(n, acc)
    n = len(struc)
    H = np.zeros((n, n), dtype=float)

    for i in range(n):
        for j in range(n):
            leng = np.linalg.norm(struc[i] - struc[j])
            if 0.9 * acc < leng < 1.1 * acc:
                H[i, j] = t

    return H