In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.linalg import eigh
from LCAO_Ham import *

In [2]:
eps0 = 0
t = -1
s = 0


x = nearestneighbor('C60.xyz')
H, S = LCAO_Ham(x, eps0, t, s)

print(x)

E, C = eigh(H, S)
print('E-value:', E)
print('E-vector', C)

(60, 'Fullerene', [[['C', 1], [2, 3, 12]], [['C', 2], [1, 4, 6]], [['C', 3], [1, 11, 35]], [['C', 4], [2, 5, 33]], [['C', 5], [4, 8, 38]], [['C', 6], [2, 7, 13]], [['C', 7], [6, 8, 54]], [['C', 8], [5, 7, 59]], [['C', 9], [10, 11, 20]], [['C', 10], [9, 12, 14]], [['C', 11], [3, 9, 19]], [['C', 12], [1, 10, 13]], [['C', 13], [6, 12, 16]], [['C', 14], [10, 15, 21]], [['C', 15], [14, 16, 50]], [['C', 16], [13, 15, 55]], [['C', 17], [18, 19, 28]], [['C', 18], [17, 20, 22]], [['C', 19], [11, 17, 27]], [['C', 20], [9, 18, 21]], [['C', 21], [14, 20, 24]], [['C', 22], [18, 23, 29]], [['C', 23], [22, 24, 46]], [['C', 24], [21, 23, 51]], [['C', 25], [26, 27, 36]], [['C', 26], [25, 28, 30]], [['C', 27], [19, 25, 35]], [['C', 28], [17, 26, 29]], [['C', 29], [22, 28, 32]], [['C', 30], [26, 31, 37]], [['C', 31], [30, 32, 42]], [['C', 32], [29, 31, 47]], [['C', 33], [4, 34, 35]], [['C', 34], [33, 36, 38]], [['C', 35], [3, 27, 33]], [['C', 36], [25, 34, 37]], [['C', 37], [30, 36, 40]], [['C', 38], [5,

In [3]:
file = open('C60.xyz')
data = file.readlines()

n = int(data[0])
species = data[1]
atomlist = []
coordlist = []

if n != (len(data)-2):
    raise ValueError('n and number of atoms input mismatch')
    
for i in range(n):
    # try:
    #     row = data[i+2].split()
    # except:
    #     print('error')
    #     break
    row = data[i+2].split()
    atomlist.append([row[0], i+1])
    coordrow = list(map(float, row[1:4]))
    coordlist.append(np.array(coordrow))

coordlist = np.array(coordlist)

print(coordlist)

[[ 2.1665  0.5906  2.5874]
 [ 3.0378  0.1766  1.5918]
 [ 1.2786 -0.3098  3.1679]
 [ 3.0118 -1.1434  1.1654]
 [ 3.1034 -1.4335 -0.193 ]
 [ 3.1503  1.2106  0.6682]
 [ 3.2428  0.9149 -0.6859]
 [ 3.2192 -0.4023 -1.1207]
 [-0.4393  1.3527  3.1271]
 [ 0.4363  2.2618  2.5542]
 [-0.0296  0.0633  3.4379]
 [ 1.7442  1.879   2.283 ]
 [ 2.3519  2.2676  1.099 ]
 [-0.2633  3.0268  1.6326]
 [ 0.3374  3.4054  0.4373]
 [ 1.6516  3.0278  0.1707]
 [-2.0903 -0.8225  2.5955]
 [-2.5111  0.4664  2.2854]
 [-0.8449 -1.0252  3.1738]
 [-1.6874  1.5533  2.5512]
 [-1.5843  2.5858  1.6319]
 [-3.2314  0.4061  1.1007]
 [-3.1227  1.441   0.1746]
 [-2.2947  2.5291  0.4399]
 [-0.4908 -2.9133  1.7365]
 [-1.743  -2.7124  1.1637]
 [-0.0393 -2.0684  2.7453]
 [-2.5486 -1.665   1.5942]
 [-3.2602 -0.9141  0.6701]
 [-1.6543 -3.0061 -0.1897]
 [-2.3542 -2.2439 -1.117 ]
 [-3.1643 -1.1949 -0.6878]
 [ 2.1364 -2.0553  1.7358]
 [ 1.6895 -2.9009  0.7293]
 [ 1.2785 -1.6366  2.7435]
 [ 0.3678 -3.3327  0.7302]
 [-0.344  -3.3904 -0.4594]
 

In [4]:
def interatomic_distance(atom1coord, atom2coord):
    #atomcoord = array berisi xyz
    deltax = atom1coord[0] - atom2coord[0]
    deltay = atom1coord[1] - atom2coord[1]
    deltaz = atom1coord[2] - atom2coord[2]

    r = np.sqrt(deltax ** 2 + deltay ** 2 + deltaz ** 2)
    return r

def rel_err(a, b):
    return abs(a - b) / b

min_distance_tol = 0.01
min_distance_list = []

for i in range(n):
    atomcoord_i = coordlist[i]
    id_i = atomlist[i]
    min_distance = 0

    for j in range(n):
        if i == j :
            continue
        atomcoord_j = coordlist[j]
        distance_ij = interatomic_distance(atomcoord_i, atomcoord_j)
        if min_distance == 0:
            min_distance = distance_ij
            nearest_neighbor = [j+1]
        else:
            if rel_err(distance_ij, min_distance) < min_distance_tol:
                nearest_neighbor.append(j+1)
            else:
                if distance_ij < min_distance:
                    min_distance = distance_ij
                    nearest_neighbor = [j+1]

    min_distance_list.append([id_i, nearest_neighbor])
                
print(min_distance_list)

[[['C', 1], [2, 3, 12]], [['C', 2], [1, 4, 6]], [['C', 3], [1, 11, 35]], [['C', 4], [2, 5, 33]], [['C', 5], [4, 8, 38]], [['C', 6], [2, 7, 13]], [['C', 7], [6, 8, 54]], [['C', 8], [5, 7, 59]], [['C', 9], [10, 11, 20]], [['C', 10], [9, 12, 14]], [['C', 11], [3, 9, 19]], [['C', 12], [1, 10, 13]], [['C', 13], [6, 12, 16]], [['C', 14], [10, 15, 21]], [['C', 15], [14, 16, 50]], [['C', 16], [13, 15, 55]], [['C', 17], [18, 19, 28]], [['C', 18], [17, 20, 22]], [['C', 19], [11, 17, 27]], [['C', 20], [9, 18, 21]], [['C', 21], [14, 20, 24]], [['C', 22], [18, 23, 29]], [['C', 23], [22, 24, 46]], [['C', 24], [21, 23, 51]], [['C', 25], [26, 27, 36]], [['C', 26], [25, 28, 30]], [['C', 27], [19, 25, 35]], [['C', 28], [17, 26, 29]], [['C', 29], [22, 28, 32]], [['C', 30], [26, 31, 37]], [['C', 31], [30, 32, 42]], [['C', 32], [29, 31, 47]], [['C', 33], [4, 34, 35]], [['C', 34], [33, 36, 38]], [['C', 35], [3, 27, 33]], [['C', 36], [25, 34, 37]], [['C', 37], [30, 36, 40]], [['C', 38], [5, 34, 39]], [['C', 